plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

title: "Rail Crowds Observatory"
description: "Evaluating crowd risks, management levers and congestion levels in a railway context"

include: ["_pages"]

defaults:
  # _obs
  - scope:
      path: ""
      type: obs
    values:
      sidebar:
        nav: "obs"
